### ISSUE TITLE
v1.9.0 不能运行

### ISSUE THREAD

**Issue by ifsc01** [Xmader/aria-ng-gui#14]
下载完打开就这样了

![image](https://user-images.githubusercontent.com/33216463/53492060-e7eb2000-3ad2-11e9-81c5-3446f6c4084b.png)

```
Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/q_/bmw7x38529lg5zjm9wb7v0cr0000gn/T/AppTranslocation/5E871478-ADFC-4DD9-9027-E6EE5BB0AA7D/d/AriaNgGUI.app/Contents/Resources/app/aria2/aria2.conf'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.writeFileSync (fs.js:1321:33)
    at edit_conf (/private/var/folders/q_/bmw7x38529lg5zjm9wb7v0cr0000gn/T/AppTranslocation/5E871478-ADFC-4DD9-9027-E6EE5BB0AA7D/d/AriaNgGUI.app/Contents/Resources/app/edit_conf.js:41:8)
    at App.<anonymous> (/private/var/folders/q_/bmw7x38529lg5zjm9wb7v0cr0000gn/T/AppTranslocation/5E871478-ADFC-4DD9-9027-E6EE5BB0AA7D/d/AriaNgGUI.app/Contents/Resources/app/app.js:58:5)
    at App.emit (events.js:187:15)
```

**Comment by Xmader** [comment]
你好，
AriaNg GUI 需要完全解压后才能打开

**Comment by ifsc01** [comment]
啥叫完全解压，mac下不就是双击app

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: Xmader <notifications@github.com>
发送时间: 星期四, 二月 28, 2019 12:35 上午
收件人: Xmader/aria-ng-gui
抄送: ifsc01; Author
主题: Re: [Xmader/aria-ng-gui] v1.9.0 不能运行 (#14)


你好，
AriaNg GUI 需要完全解压后才能打开

―

**Comment by Xmader** [comment]
抱歉，我对 MacOS 不熟悉，我误认为你是从一个解压缩软件中打开 AriaNgGUI.app

由于 MacOS 上的 App Translocation 机制，在 `~/Downloads` 文件夹中打开的 APP 会被自动挂载到一个只读文件系统，需要将它移动到其它的文件夹中（通常是 `/Applications` 中）才能正常打开

参考：https://lapcatsoftware.com/articles/app-translocation.html
