### ISSUE TITLE
macOS Node.js v20.6.0 error

### ISSUE THREAD

**Issue by betta-cyber** [Xmader/aria-ng-gui#59]
install  by `npm i -g aria-ng-gui`

got error

```
npm ERR! code 1
npm ERR! path /opt/homebrew/lib/node_modules/aria-ng-gui
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /opt/homebrew/lib/node_modules/aria-ng-gui/download.js:62
npm ERR!         const remoteDataSHA256 = sha256sum.match(`(\\w{64}) \\*${fileName}`)[1]
npm ERR!                                                                             ^
npm ERR!
npm ERR! TypeError: Cannot read properties of null (reading '1')
npm ERR!     at downloadArtifact (/opt/homebrew/lib/node_modules/aria-ng-gui/download.js:62:77)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!
npm ERR! Node.js v20.6.0
```

**Comment by guoguoaidaogu** [comment]
Same error on macOS with node v26.7.0:
```
➜  ~ npm i -g aria-ng-gui
npm error code 1
npm error path /opt/homebrew/lib/node_modules/aria-ng-gui
npm error command failed
npm error command sh -c node install.js
npm error /opt/homebrew/lib/node_modules/aria-ng-gui/download.js:62
npm error         const remoteDataSHA256 = sha256sum.match(`(\\w{64}) \\*${fileName}`)[1]
npm error                                                                             ^
npm error
npm error TypeError: Cannot read properties of null (reading '1')
npm error     at downloadArtifact (/opt/homebrew/lib/node_modules/aria-ng-gui/download.js:62:77)
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
npm error
npm error Node.js v26.7.0
npm error A complete log of this run can be found in: (omitted)
```

```
➜  ~ node -v
v26.7.0
➜  ~ npm -v 
11.19.0
```
Meanwhile the release file [AriaNgGUI-darwin-x64.zip](https://github.com/Xmader/aria-ng-gui/releases/download/v3.1.2/AriaNgGUI-darwin-x64.zip) at `v3.1.2` seems not to work either on Apple Silicon (Rosetta 2). I began to wonder if there is a macOS alternative application.
